name = "census-2027-bhawraguri-portal"
compatibility_date = "2026-09-12"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "census-2027-bhawraguri"
database_id = "74aa711d-ebc8-4fde-bf65-223cab5bbf8e"
